---
ci:
  skip: [flake8]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
<<<<<<< HEAD
    rev: v5.0.0
=======
    rev: v4.6.0
>>>>>>> e25ca5e221 (CI(deps): Update pre-commit hook pre-commit/pre-commit-hooks to v4.6.0 (#3854))
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)^(
                configure$|
                .*\.ascii$|
                .*\.asc$|
                .*\.ref$|
                raster3d/r3.null/testsuite/data/test_volume_.*|
                mswindows/.*|
                .*\.po$|
                .*\.ps$|
                .*\.svg$|
                python/libgrass_interface_generator/ctypesgen/|
                lib/fonts/fonts/.*
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
                configure$|
                .*\.ascii$|
                .*\.asc$|
                .*\.ref$|
                python/grass/pygrass/raster/testsuite/data/geology_cats|
                mswindows/.*|
                .*\.po$|
                .*\.ps$|
                .*\.svg$|
                python/libgrass_interface_generator/ctypesgen/|
                lib/fonts/fonts/.*
          )
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    rev: v0.5.1
=======
    rev: v0.5.4
>>>>>>> main
=======
    rev: v0.5.5
>>>>>>> osgeo-main
=======
    rev: v0.5.7
>>>>>>> osgeo-main
=======
    rev: v0.6.2
>>>>>>> osgeo-main
=======
    rev: v0.6.3
>>>>>>> osgeo-main
=======
    rev: v0.6.9
>>>>>>> osgeo-main
=======
    rev: v0.7.0
>>>>>>> osgeo-main
=======
    rev: v0.7.1
>>>>>>> osgeo-main
=======
    rev: v0.7.2
>>>>>>> 0824e8842e (CI(deps): Update ruff to v0.7.2 (#4631))
=======
    rev: v0.7.3
<<<<<<< HEAD
>>>>>>> osgeo-main
=======
=======
=======
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
<<<<<<< HEAD
    rev: v0.5.1
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix, --preview]
>>>>>>> deff63f816 (checks(ruff): Configure ruff linter (#3972))
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
>>>>>>> bfd472d489 (CI(deps): Update pre-commit hook igorshubovych/markdownlint-cli to v0.41.0 (#3844))
<<<<<<< HEAD
>>>>>>> 756344f217 (CI(deps): Update pre-commit hook igorshubovych/markdownlint-cli to v0.41.0 (#3844))
=======
=======
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    rev: v0.5.1
=======
    rev: v0.5.4
>>>>>>> main
=======
    rev: v0.5.5
>>>>>>> osgeo-main
=======
    rev: v0.5.7
>>>>>>> osgeo-main
=======
    rev: v0.6.2
>>>>>>> osgeo-main
=======
    rev: v0.6.3
>>>>>>> osgeo-main
=======
    rev: v0.6.9
>>>>>>> osgeo-main
=======
    rev: v0.7.0
>>>>>>> osgeo-main
=======
    rev: v0.7.1
>>>>>>> osgeo-main
=======
    rev: v0.7.2
>>>>>>> 0824e8842e (CI(deps): Update ruff to v0.7.2 (#4631))
>>>>>>> 79c03e82ac (CI(deps): Update ruff to v0.7.2 (#4631))
>>>>>>> 2d8985db52 (CI(deps): Update ruff to v0.7.2 (#4631))
=======
    rev: v0.7.4
>>>>>>> d5584063f5 (CI(deps): Update ruff to v0.7.4 (#4705))
=======
    rev: v0.8.0
>>>>>>> f1093bdc6a (CI(deps): Update ruff to v0.8.0 (#4738))
=======
=======
>>>>>>> d77766906a (checks(ruff): Configure ruff linter (#3972))
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
<<<<<<< HEAD
    rev: v0.8.0
=======
    rev: v0.7.3
=======
=======
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.1
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix, --preview]
>>>>>>> deff63f816 (checks(ruff): Configure ruff linter (#3972))
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
>>>>>>> bfd472d489 (CI(deps): Update pre-commit hook igorshubovych/markdownlint-cli to v0.41.0 (#3844))
>>>>>>> 756344f217 (CI(deps): Update pre-commit hook igorshubovych/markdownlint-cli to v0.41.0 (#3844))
>>>>>>> 83349cd07f (CI(deps): Update pre-commit hook igorshubovych/markdownlint-cli to v0.41.0 (#3844))
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --preview]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint-fix
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
<<<<<<< HEAD
    rev: 24.10.0
=======
    rev: 24.4.2
>>>>>>> 078ff8fdc7 (CI(deps): Update pre-commit hook psf/black-pre-commit-mirror to v24.4.2 (#3842))
    hooks:
      - id: black-jupyter
        exclude: |
          (?x)^(
                python/libgrass_interface_generator/
          )
  - repo: https://github.com/pycqa/flake8
<<<<<<< HEAD
    rev: 7.1.1
=======
    rev: 5.0.4
>>>>>>> 0f21b674b1 (CI(deps): Update dependency flake8 to v5 (#3815))
    hooks:
      - id: flake8
        exclude: |
          (?x)^(
                python/libgrass_interface_generator/|
                .*/testsuite/.*
          )
  - repo: https://github.com/pre-commit/mirrors-clang-format
<<<<<<< HEAD
    rev: v18.1.8
=======
    rev: v15.0.7
>>>>>>> f16276e41c (CI(deps): Update pre-commit hook pre-commit/mirrors-clang-format to v15.0.7 (#3841))
    hooks:
      - id: clang-format
        types_or: [c, c++, javascript, json, objective-c]
        exclude: |
          (?x)^(
                man/jquery.fixedheadertable.min.js$|
                .*\.ipynb$
          )
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
