---
name: pytest

on:
  push:
    branches:
      - main
      - releasebranch_*
  pull_request:

jobs:
  pytest:
    concurrency:
      group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}-${{
        matrix.os }}-${{ matrix.python-version }}
      cancel-in-progress: true

    strategy:
      matrix:
        os:
          - ubuntu-22.04
        python-version:
          - '3.9'
          - '3.12'
          - '3.13'
      fail-fast: true

    runs-on: ${{ matrix.os }}
    env:
      FORCE_COLOR: 1 # for software including pip: https://force-color.org/
      CLICOLOR_FORCE: 1 # for other software including ninja: https://bixense.com/clicolors/
      PYTHONWARNINGS: always

    steps:
<<<<<<< HEAD
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
=======
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
>>>>>>> d4a11a7eae (CI(deps): Update actions/checkout action to v4.1.7 (#3801))

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          allow-prereleases: true

      - name: Install non-Python dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget git gawk findutils
          xargs -a <(awk '! /^ *(#|$)/' ".github/workflows/apt.txt") -r -- \
              sudo apt-get install -y --no-install-recommends --no-install-suggests

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 07d8b5385f (CI(deps): Update rui314/setup-mold digest to 65685f4 (#3858))
      - uses: rui314/setup-mold@b015f7e3f2938ad3a5ed6e5111a8c6c7c1d6db6e # v1
=======
      - uses: rui314/setup-mold@65685f45207903d37d006cd402c397653c57660e # v1
>>>>>>> e253d18cba (CI(deps): Update rui314/setup-mold digest to 65685f4 (#3858))
<<<<<<< HEAD
=======
      - uses: rui314/setup-mold@2e332a0b602c2fc65d2d3995941b1b29a5f554a0 # v1
>>>>>>> 7c0ad8584e (CI(deps): Update rui314/setup-mold digest to 2e332a0 (#3989))
=======
>>>>>>> 07d8b5385f (CI(deps): Update rui314/setup-mold digest to 65685f4 (#3858))

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/python_requirements.txt
          pip install -r .github/workflows/optional_requirements.txt
          pip install pytest pytest-timeout pytest-github-actions-annotate-failures pytest-xdist pytest-cov

      - name: Create installation directory
        run: |
          mkdir $HOME/install

      - name: Set number of cores for compilation
        run: |
          echo "MAKEFLAGS=-j$(nproc)" >> $GITHUB_ENV

      - name: Build
        run: .github/workflows/build_${{ matrix.os }}.sh $HOME/install

      - name: Add the bin directory to PATH
        run: |
          echo "$HOME/install/bin" >> $GITHUB_PATH

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> c439bf056d (version: Start 8.5.0dev (#3789))
=======
>>>>>>> 0cfb7b5738 (CI: Initial code coverage configuration with Codecov (#3905))
=======
      - name: Test executing of the grass command
        run: .github/workflows/test_simple.sh

      - name: Run pytest
        run: |
          export PYTHONPATH=`grass --config python_path`:$PYTHONPATH
          export LD_LIBRARY_PATH=$(grass --config path)/lib:$LD_LIBRARY_PATH
          pytest --verbose --color=yes --durations=0 --durations-min=0.5 --numprocesses auto -ra .

>>>>>>> c4b5697244 (version: Start 8.5.0dev (#3789))
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> d0300d79d5 (CI: Initial code coverage configuration with Codecov (#3905))
=======
>>>>>>> c439bf056d (version: Start 8.5.0dev (#3789))
=======
=======
>>>>>>> d0300d79d5 (CI: Initial code coverage configuration with Codecov (#3905))
>>>>>>> 0cfb7b5738 (CI: Initial code coverage configuration with Codecov (#3905))
      - name: Print installed versions
        if: always()
        run: .github/workflows/print_versions.sh

      - name: Test executing of the grass command
        run: .github/workflows/test_simple.sh

      - name: Run pytest with multiple workers in parallel
        run: |
          export PYTHONPATH=`grass --config python_path`:$PYTHONPATH
          export LD_LIBRARY_PATH=$(grass --config path)/lib:$LD_LIBRARY_PATH
          export INITIAL_GISBASE="$(grass --config path)"
          export INITIAL_PWD="${PWD}"
          pytest --verbose --color=yes --durations=0 --durations-min=0.5 \
            --numprocesses auto \
            --cov \
            --cov-context=test \
            -ra . \
            -m 'not needs_solo_run'

      - name: Run pytest with a single worker (for tests marked with needs_solo_run)
        run: |
          export PYTHONPATH=`grass --config python_path`:$PYTHONPATH
          export LD_LIBRARY_PATH=$(grass --config path)/lib:$LD_LIBRARY_PATH
          export INITIAL_GISBASE="$(grass --config path)"
          export INITIAL_PWD="${PWD}"
          pytest --verbose --color=yes --durations=0 --durations-min=0.5 \
            --cov \
<<<<<<< HEAD
            --cov-context=test \
            --cov-append \
=======
>>>>>>> d0300d79d5 (CI: Initial code coverage configuration with Codecov (#3905))
            -ra . \
            -m 'needs_solo_run'
      - name: Fix non-standard installed script paths in coverage data
        run: |
          export PYTHONPATH=`grass --config python_path`:$PYTHONPATH
          export LD_LIBRARY_PATH=$(grass --config path)/lib:$LD_LIBRARY_PATH
          export INITIAL_GISBASE="$(grass --config path)"
          export INITIAL_PWD="${PWD}"
          python utils/coverage_mapper.py
          coverage combine
          coverage html

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@015f24e6818733317a2da2edd6290ab26238649a # v5.0.7
        with:
          verbose: true
          flags: pytest-python-${{ matrix.python-version }}
          name: pytest-python-${{ matrix.python-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Make python-only code coverage test report available
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: python-codecoverage-report-${{ matrix.os }}-${{ matrix.python-version }}
          path: coverage_html_report
          retention-days: 1

<<<<<<< HEAD
=======
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          verbose: true
          flags: pytest-python-${{ matrix.python-version }}
          name: pytest-python-${{ matrix.python-version }}
          token: ${{ secrets.CODECOV_TOKEN }}

>>>>>>> d0300d79d5 (CI: Initial code coverage configuration with Codecov (#3905))
  pytest-success:
    name: pytest Result
    needs:
      - pytest
    if: ${{ always() }}
    uses: ./.github/workflows/verify-success.yml
    with:
      needs_context: ${{ toJson(needs) }}
