---
name: General linting

on:
  push:
    branches:
      - main
      - releasebranch_*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  super-linter:
    name: GitHub Super Linter

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
<<<<<<< HEAD
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
=======
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
>>>>>>> d4a11a7eae (CI(deps): Update actions/checkout action to v4.1.7 (#3801))
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - name: Lint code base
<<<<<<< HEAD
<<<<<<< HEAD
        uses: super-linter/super-linter/slim@b92721f792f381cedc002ecdbb9847a15ece5bb8 # v7.1.0
=======
        uses: super-linter/super-linter/slim@3fe03abab2eafb293ace16d4a3b07aeabcb3f1a0 # v6.7.0
>>>>>>> 31def23932 (CI(deps): Update super-linter/super-linter action to v6.7.0 (#4002))
=======
        uses: super-linter/super-linter/slim@e1cb86b6e8d119f789513668b4b30bf17fe1efe4 # v7.2.0
>>>>>>> f62faf221d (CI(deps): Update super-linter/super-linter action to v7.2.0 (#4713))
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # By default, super-linter expect all linters to have their config
          # files inside .github/linters.
          # Setting it to the root of the repo for easier configuration here.
          LINTER_RULES_PATH: .
          # Listed but commented out linters would be nice to have.
          # (see https://github.com/github/super-linter#environment-variables)
          #
          # Python (supported using Pylint) and C/C++ (not supported) are
          # handled separately due to the complexity of the settings.
          # VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          # VALIDATE_CSS: true
          # VALIDATE_DOCKER: true
          VALIDATE_JAVASCRIPT_ES: true
          # VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_POWERSHELL: true
          # VALIDATE_XML: true
          VALIDATE_YAML: true
          MARKDOWN_CONFIG_FILE: .markdownlint.yml
          YAML_CONFIG_FILE: .yamllint
