---
name: Nix package and environment

on:
  schedule:
    - cron: '0 1 * * 1'
  push:
    tags:
      - '*'
<<<<<<< HEAD
  pull_request:
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'package.nix'
      - '.github/workflows/test-nix.yml'
=======
>>>>>>> 0774593dac (CI: add nix package build test (#3906))
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  test-nix:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
<<<<<<< HEAD
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install nix
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        uses: DeterminateSystems/nix-installer-action@7993355175c2765e5733dae74f3e0786fe0e5c4f # v12
=======
        uses: DeterminateSystems/nix-installer-action@ab6bcb2d5af0e904d04aea750e2089e9dc4cbfdd # v13
>>>>>>> main
=======
        uses: DeterminateSystems/nix-installer-action@da36cb69b1c3247ad7a1f931ebfd954a1105ef14 # v14
>>>>>>> osgeo-main
=======
        uses: DeterminateSystems/nix-installer-action@b92f66560d6f97d6576405a7bae901ab57e72b6a # v15
>>>>>>> 7cd22e98da (CI(deps): Update DeterminateSystems/nix-installer-action action to v15 (#4645))
=======
        uses: DeterminateSystems/nix-installer-action@b92f66560d6f97d6576405a7bae901ab57e72b6a # v15
>>>>>>> osgeo-main
=======
        uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
>>>>>>> osgeo-main

      - name: Setup cachix
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
=======
<<<<<<< HEAD
=======
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install nix
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 24fe48ef5f (CI: add nix package build test (#3906))
        uses: DeterminateSystems/nix-installer-action@v12
=======
=======
>>>>>>> fe73274726 (CI: add nix package build test (#3906))
=======
>>>>>>> 64b723ae3a (CI(deps): Pin dependencies (#3932))
        uses: DeterminateSystems/nix-installer-action@7993355175c2765e5733dae74f3e0786fe0e5c4f # v12
>>>>>>> 90307bc0bb (CI(deps): Pin dependencies (#3932))

      - name: Setup cachix
<<<<<<< HEAD
        uses: cachix/cachix-action@v15
<<<<<<< HEAD
>>>>>>> 3986103fdf (CI: add nix package build test (#3906))
=======
        uses: DeterminateSystems/nix-installer-action@7993355175c2765e5733dae74f3e0786fe0e5c4f # v12

      - name: Setup cachix
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
>>>>>>> ab79e435cc (CI(deps): Pin dependencies (#3932))
=======
>>>>>>> 0774593dac (CI: add nix package build test (#3906))
<<<<<<< HEAD
>>>>>>> 24fe48ef5f (CI: add nix package build test (#3906))
=======
=======
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
<<<<<<< HEAD
>>>>>>> 4ac7be496d (CI(deps): Pin dependencies (#3932))
<<<<<<< HEAD
>>>>>>> 90307bc0bb (CI(deps): Pin dependencies (#3932))
=======
=======
=======
        uses: DeterminateSystems/nix-installer-action@v12

      - name: Setup cachix
        uses: cachix/cachix-action@v15
>>>>>>> 3986103fdf (CI: add nix package build test (#3906))
<<<<<<< HEAD
>>>>>>> 0143a3f5d7 (CI: add nix package build test (#3906))
<<<<<<< HEAD
>>>>>>> fe73274726 (CI: add nix package build test (#3906))
=======
=======
=======
        uses: DeterminateSystems/nix-installer-action@7993355175c2765e5733dae74f3e0786fe0e5c4f # v12

      - name: Setup cachix
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
>>>>>>> ab79e435cc (CI(deps): Pin dependencies (#3932))
>>>>>>> a6fb488c35 (CI(deps): Pin dependencies (#3932))
>>>>>>> 64b723ae3a (CI(deps): Pin dependencies (#3932))
        with:
          name: osgeo-grass
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build package
        run: nix build -L --accept-flake-config .#grass

      - name: Test development environment
        run: nix develop --accept-flake-config --command echo OK
